onEvent("item.registry", event => {
    event.create("scrap")
        .displayName('锻造废料')
    event.create("silver_key")
        .displayName('银钥匙')
        .maxStackSize(1)
    event.create("sium")
        .displayName(Text.of('锐器升级材料').color(0x1E90FF))
        .maxStackSize(1)
    event.create("bium")
        .displayName('钝器升级材料')
        .maxStackSize(1)
    event.create("sum")
        .displayName('利器升级材料')
        .maxStackSize(1)
    event.create("stay")
        .displayName(' ')
        .maxStackSize(1)
    event.create("sium_advanced_orb")
        .displayName(' ')
        .maxStackSize(1)
    event.create("bium_advanced_orb")
        .displayName(' ')
        .maxStackSize(1)
    event.create("sum_advanced_orb")
        .displayName(' ')
        .maxStackSize(1)
    event.create("companion_scrolls")
        .displayName('随传卷轴')
})