#Better Weather uses a prefix system for what biomes weather is allowed to function in.
# Prefix Guide:
# "#" - Biome category representable.
# "$" - Biome dictionary representable.
# "," - Creates a new condition, separate from the previous.
# "ALL" - Spawn in all biomes(no condition).
# "!" - Negates/flips/does the reverse of the condition.
# "" - No prefix serves as a biome ID OR Mod ID representable.
#
# Here are a few examples:
#1. "byg#THE_END, $OCEAN" would mean that the ore may spawn in biomes with the name space "byg" AND in the "END" biome category, OR all biomes in the "OCEAN" dictionary.
#2. "byg:guiana_shield, #MESA" would mean that the ore may spawn in the "byg:guiana_shield" OR all biomes in the "MESA" category.
#3. "byg#ICY$MOUNTAIN" would mean that the ore may only spawn in biomes from byg in the "ICY" category and "MOUNTAIN" dictionary type.
#4. "!byg#DESERT" would mean that the ore may only spawn in biomes that are NOT from byg and NOT in the "DESERT" category.
#5. "ALL", spawn everywhere. 
#6. "" Don't spawn anywhere.
biomeCondition = "!#DESERT#SAVANNA#NETHER#THEEND"
#The chance of a chunk being ticked for this tick.
chunkTickChance = 150
#What is the default chance for this weather event to occur? This value is only used when Seasons are NOT present in the given dimension.
defaultChance = 0.25
#The chance of an entity getting damaged every tick when acid rain is on the player's position.
entityDamageChance = 100
#What is the temperature offset for valid biomes?
humidityOffset = 0.1
#Determines whether or not this weather event may spawn lightning and sets world info internally for MC and mods to use.
isThundering = false
#How often does lightning spawn? Requires "isThundering" to be true.
lightningChance = 0
#What is the temperature offset for valid biomes?
temperatureOffset = 0.0
#Target Weather Event's Registry ID to configure settings for in this config.
type = "betterweather:acid_rain"

[clientSettings]
	#How dense is fog?
	fogDensity = -1.0
	#Texture path to the rain texture.
	rainTexture = "betterweather:textures/environment/acid_rain.png"
	#What is the opacity of the sky? 0.0 means hidden, 1.0 is fully visible.
	##Range 0.0-1.0
	skyOpacity = 0.0
	#Texture path to the rain texture.
	snowTexture = "minecraft:textures/environment/snow.png"
	#Do sunsets/sunrises modify fog/sky color?
	sunsetSunriseColor = true
	#Target Weather Event's Registry ID to configure settings for in this config.
	type = "betterweather:rain"

	[clientSettings.colorSettings]
		#The strength of this world's cloud color blend towards the value of "cloudTargetHexColor".
		#Range: 0 - 1.0
		cloudColorBlendStrength = 1.0
		#Blends this world's grass color towards this value. Blend strength is determined by the value of "cloudColorBlendStrength".
		cloudTargetHexColor = "ff59648e"
		#The strength of this world's fog color blend towards the value of "fogTargetHexColor".
		#Range: 0 - 1.0
		fogColorBlendStrength = 1.0
		#Blends the world's fog color towards this value. Blend strength is determined by the value of "fogColorBlendStrength".
		fogTargetHexColor = "ff59648e"
		#The strength of this world's sky color blend towards the value of "foliageTargetHexColor".
		#Range: 0 - 1.0
		foliageColorBlendStrength = 0.1
		#Blends this world's foliage color towards this value. Blend strength is determined by the value of "foliageColorBlendStrength".
		foliageTargetHexColor = ""
		#The strength of this world's grass color blend towards the value of "grassTargetHexColor".
		#Range: 0 - 1.0
		grassColorBlendStrength = 0.1
		#Blends this world's grass color towards this value. Blend strength is determined by the value of "grassColorBlendStrength".
		grassTargetHexColor = ""
		#The strength of this world's sky color blend towards the value of "skyTargetHexColor".
		#Range: 0 - 1.0
		skyColorBlendStrength = 1.0
		#Blends this world's grass color towards this value. Blend strength is determined by the value of "skyColorBlendStrength".
		skyTargetHexColor = "ff677288"

#What the specified block(left) "decays" into(right).
[decayer]
	"alexsmobs:banana_peel" = "minecraft:air"
	"betterendforge:amber_root_seed" = "minecraft:air"
	"betterendforge:aurant_polypore" = "minecraft:air"
	"betterendforge:blossom_berry_seed" = "minecraft:air"
	"betterendforge:blue_vine" = "minecraft:air"
	"betterendforge:blue_vine_seed" = "minecraft:air"
	"betterendforge:bulb_moss" = "minecraft:air"
	"betterendforge:bulb_vine" = "minecraft:air"
	"betterendforge:bulb_vine_seed" = "minecraft:air"
	"betterendforge:cave_bush" = "minecraft:air"
	"betterendforge:chorus_mushroom_seed" = "minecraft:air"
	"betterendforge:creeping_moss" = "minecraft:air"
	"betterendforge:cyan_moss" = "minecraft:air"
	"betterendforge:dense_vine" = "minecraft:air"
	"betterendforge:dragon_tree_leaves" = "minecraft:air"
	"betterendforge:dragon_tree_sapling" = "minecraft:air"
	"betterendforge:end_lotus_flower" = "minecraft:air"
	"betterendforge:end_lotus_leaf" = "minecraft:air"
	"betterendforge:filalux" = "minecraft:air"
	"betterendforge:filalux_wings" = "minecraft:air"
	"betterendforge:flamaea" = "minecraft:air"
	"betterendforge:glowing_pillar_luminophor" = "minecraft:air"
	"betterendforge:glowing_pillar_roots" = "minecraft:air"
	"betterendforge:glowing_pillar_seed" = "minecraft:air"
	"betterendforge:helix_tree_leaves" = "minecraft:air"
	"betterendforge:helix_tree_sapling" = "minecraft:air"
	"betterendforge:hydralux_petal_block" = "minecraft:air"
	"betterendforge:hydralux_petal_block_black" = "minecraft:air"
	"betterendforge:hydralux_petal_block_blue" = "minecraft:air"
	"betterendforge:hydralux_petal_block_brown" = "minecraft:air"
	"betterendforge:hydralux_petal_block_cyan" = "minecraft:air"
	"betterendforge:hydralux_petal_block_gray" = "minecraft:air"
	"betterendforge:hydralux_petal_block_green" = "minecraft:air"
	"betterendforge:hydralux_petal_block_light_blue" = "minecraft:air"
	"betterendforge:hydralux_petal_block_light_gray" = "minecraft:air"
	"betterendforge:hydralux_petal_block_lime" = "minecraft:air"
	"betterendforge:hydralux_petal_block_magenta" = "minecraft:air"
	"betterendforge:hydralux_petal_block_orange" = "minecraft:air"
	"betterendforge:hydralux_petal_block_pink" = "minecraft:air"
	"betterendforge:hydralux_petal_block_purple" = "minecraft:air"
	"betterendforge:hydralux_petal_block_red" = "minecraft:air"
	"betterendforge:hydralux_petal_block_white" = "minecraft:air"
	"betterendforge:hydralux_petal_block_yellow" = "minecraft:air"
	"betterendforge:jungle_fern" = "minecraft:air"
	"betterendforge:jungle_vine" = "minecraft:air"
	"betterendforge:lacugrove_leaves" = "minecraft:air"
	"betterendforge:lacugrove_sapling" = "minecraft:air"
	"betterendforge:lanceleaf" = "minecraft:air"
	"betterendforge:lanceleaf_seed" = "minecraft:air"
	"betterendforge:large_amaranita_mushroom" = "minecraft:air"
	"betterendforge:lucernia_leaves" = "minecraft:air"
	"betterendforge:lucernia_sapling" = "minecraft:air"
	"betterendforge:lumecorn_seed" = "minecraft:air"
	"betterendforge:mossy_glowshroom_sapling" = "minecraft:air"
	"betterendforge:murkweed" = "minecraft:air"
	"betterendforge:needlegrass" = "minecraft:air"
	"betterendforge:purple_polypore" = "minecraft:air"
	"betterendforge:pythadendron_leaves" = "minecraft:air"
	"betterendforge:pythadendron_sapling" = "minecraft:air"
	"betterendforge:rubinea" = "minecraft:air"
	"betterendforge:ruscus" = "minecraft:air"
	"betterendforge:shadow_berry" = "minecraft:air"
	"betterendforge:small_amaranita_mushroom" = "minecraft:air"
	"betterendforge:small_jellyshroom" = "minecraft:air"
	"betterendforge:tail_moss" = "minecraft:air"
	"betterendforge:tenanea_flowers" = "minecraft:air"
	"betterendforge:tenanea_leaves" = "minecraft:air"
	"betterendforge:tenanea_sapling" = "minecraft:air"
	"betterendforge:twisted_moss" = "minecraft:air"
	"betterendforge:twisted_umbrella_moss" = "minecraft:air"
	"betterendforge:twisted_umbrella_moss_tall" = "minecraft:air"
	"betterendforge:twisted_vine" = "minecraft:air"
	"betterendforge:umbrella_moss" = "minecraft:air"
	"betterendforge:umbrella_moss_tall" = "minecraft:air"
	"betterendforge:umbrella_tree_sapling" = "minecraft:air"
	"cinderscapes:bramble_berry_bush" = "minecraft:air"
	"cinderscapes:umbral_fungus" = "minecraft:air"
	"graveyard:moss_carpet" = "minecraft:air"
	"iceandfire:chared_grass_path" = "minecraft:air"
	"iceandfire:crackled_grass_path" = "minecraft:air"
	"iceandfire:frozen_grass_path" = "minecraft:air"
	"iceandfire:myrmex_desert_biolight" = "minecraft:air"
	"iceandfire:myrmex_jungle_biolight" = "minecraft:air"
	"iceandfire:nest" = "minecraft:air"
	"minecraft:acacia_leaves" = "minecraft:air"
	"minecraft:acacia_sapling" = "minecraft:air"
	"minecraft:allium" = "minecraft:air"
	"minecraft:attached_melon_stem" = "minecraft:air"
	"minecraft:attached_pumpkin_stem" = "minecraft:air"
	"minecraft:azure_bluet" = "minecraft:air"
	"minecraft:beetroots" = "minecraft:air"
	"minecraft:birch_leaves" = "minecraft:air"
	"minecraft:birch_sapling" = "minecraft:air"
	"minecraft:blue_orchid" = "minecraft:air"
	"minecraft:brown_mushroom" = "minecraft:air"
	"minecraft:carrots" = "minecraft:air"
	"minecraft:chorus_flower" = "minecraft:air"
	"minecraft:chorus_plant" = "minecraft:air"
	"minecraft:cocoa" = "minecraft:air"
	"minecraft:cornflower" = "minecraft:air"
	"minecraft:crimson_fungus" = "minecraft:air"
	"minecraft:dandelion" = "minecraft:air"
	"minecraft:dark_oak_leaves" = "minecraft:air"
	"minecraft:dark_oak_sapling" = "minecraft:air"
	"minecraft:grass_block" = "minecraft:dirt"
	"minecraft:jungle_leaves" = "minecraft:air"
	"minecraft:jungle_sapling" = "minecraft:air"
	"minecraft:lily_of_the_valley" = "minecraft:air"
	"minecraft:lily_pad" = "minecraft:air"
	"minecraft:melon_stem" = "minecraft:air"
	"minecraft:mycelium" = "minecraft:dirt"
	"minecraft:nether_wart" = "minecraft:air"
	"minecraft:oak_leaves" = "minecraft:air"
	"minecraft:oak_sapling" = "minecraft:air"
	"minecraft:orange_tulip" = "minecraft:air"
	"minecraft:oxeye_daisy" = "minecraft:air"
	"minecraft:pink_tulip" = "minecraft:air"
	"minecraft:podzol" = "minecraft:dirt"
	"minecraft:poppy" = "minecraft:air"
	"minecraft:potatoes" = "minecraft:air"
	"minecraft:pumpkin_stem" = "minecraft:air"
	"minecraft:red_mushroom" = "minecraft:air"
	"minecraft:red_tulip" = "minecraft:air"
	"minecraft:spruce_leaves" = "minecraft:air"
	"minecraft:spruce_sapling" = "minecraft:air"
	"minecraft:sugar_cane" = "minecraft:air"
	"minecraft:sweet_berry_bush" = "minecraft:air"
	"minecraft:twisting_vines" = "minecraft:air"
	"minecraft:twisting_vines_plant" = "minecraft:air"
	"minecraft:warped_fungus" = "minecraft:air"
	"minecraft:weeping_vines" = "minecraft:air"
	"minecraft:weeping_vines_plant" = "minecraft:air"
	"minecraft:wheat" = "minecraft:air"
	"minecraft:white_tulip" = "minecraft:air"
	"minecraft:wither_rose" = "minecraft:air"
	"mod_lavacow:bloodtooth_shroom" = "minecraft:air"
	"mod_lavacow:cactoid_sprout" = "minecraft:air"
	"mod_lavacow:cordy_shroom" = "minecraft:air"
	"mod_lavacow:glowshroom" = "minecraft:air"
	"mod_lavacow:veil_shroom" = "minecraft:air"
	"outer_end:azure_berry_vine" = "minecraft:air"
	"outer_end:azure_berry_vine_top" = "minecraft:air"
	"outer_end:azure_bud" = "minecraft:air"
	"outer_end:azure_leaves" = "minecraft:air"
	"quark:blue_blossom_leaves" = "minecraft:air"
	"quark:blue_blossom_sapling" = "minecraft:air"
	"quark:glowshroom" = "minecraft:air"
	"quark:lavender_blossom_leaves" = "minecraft:air"
	"quark:lavender_blossom_sapling" = "minecraft:air"
	"quark:orange_blossom_leaves" = "minecraft:air"
	"quark:orange_blossom_sapling" = "minecraft:air"
	"quark:pink_blossom_leaves" = "minecraft:air"
	"quark:pink_blossom_sapling" = "minecraft:air"
	"quark:red_blossom_leaves" = "minecraft:air"
	"quark:red_blossom_sapling" = "minecraft:air"
	"quark:yellow_blossom_leaves" = "minecraft:air"
	"quark:yellow_blossom_sapling" = "minecraft:air"
	"terrestria:agave" = "minecraft:air"
	"terrestria:aloe_vera" = "minecraft:air"
	"terrestria:bryce_sapling" = "minecraft:air"
	"terrestria:cypress_leaves" = "minecraft:air"
	"terrestria:cypress_sapling" = "minecraft:air"
	"terrestria:dark_japanese_maple_leaves" = "minecraft:air"
	"terrestria:dark_japanese_maple_sapling" = "minecraft:air"
	"terrestria:dead_grass" = "minecraft:air"
	"terrestria:hemlock_leaves" = "minecraft:air"
	"terrestria:hemlock_sapling" = "minecraft:air"
	"terrestria:indian_paintbrush" = "minecraft:air"
	"terrestria:japanese_maple_leaves" = "minecraft:air"
	"terrestria:japanese_maple_sapling" = "minecraft:air"
	"terrestria:japanese_maple_shrub_leaves" = "minecraft:air"
	"terrestria:japanese_maple_shrub_sapling" = "minecraft:air"
	"terrestria:jungle_palm_leaves" = "minecraft:air"
	"terrestria:jungle_palm_sapling" = "minecraft:air"
	"terrestria:rainbow_eucalyptus_leaves" = "minecraft:air"
	"terrestria:rainbow_eucalyptus_sapling" = "minecraft:air"
	"terrestria:redwood_leaves" = "minecraft:air"
	"terrestria:redwood_sapling" = "minecraft:air"
	"terrestria:rubber_leaves" = "minecraft:air"
	"terrestria:rubber_sapling" = "minecraft:air"
	"terrestria:saguaro_cactus_sapling" = "minecraft:air"
	"terrestria:sakura_leaves" = "minecraft:air"
	"terrestria:sakura_sapling" = "minecraft:air"
	"terrestria:tiny_cactus" = "minecraft:air"
	"terrestria:willow_leaves" = "minecraft:air"
	"terrestria:willow_sapling" = "minecraft:air"
	"terrestria:yucca_palm_leaves" = "minecraft:air"
	"terrestria:yucca_palm_sapling" = "minecraft:air"
	"traverse:brown_autumnal_leaves" = "minecraft:air"
	"traverse:brown_autumnal_sapling" = "minecraft:air"
	"traverse:fir_leaves" = "minecraft:air"
	"traverse:fir_sapling" = "minecraft:air"
	"traverse:orange_autumnal_leaves" = "minecraft:air"
	"traverse:orange_autumnal_sapling" = "minecraft:air"
	"traverse:red_autumnal_leaves" = "minecraft:air"
	"traverse:red_autumnal_sapling" = "minecraft:air"
	"traverse:yellow_autumnal_leaves" = "minecraft:air"
	"traverse:yellow_autumnal_sapling" = "minecraft:air"

#Entity/Category(left) damage strength(right).
[entityDamage]
	"category/monster" = 0.5
	"minecraft:player" = 0.5

#What is the chance for this weather event to occur for the given season (phase)?
[seasonChances]

	[seasonChances.AUTUMN]
		END = 0.03
		MID = 0.03
		START = 0.03

	[seasonChances.SPRING]
		END = 0.16
		MID = 0.26
		START = 0.23

	[seasonChances.SUMMER]
		END = 0.0
		MID = 0.0
		START = 0.03

	[seasonChances.WINTER]
		END = 0.06
		MID = 0.03
		START = 0.03

