#Set to false to disable the default way of unlocking trinkets.
unlockEnabled = true
#Cooldown (ticks) between unlocks
#Range: 0 ~ 1728000
unlockCooldown = 2400
#List of banned trinkets eg: ["losttrinkets:piggy", "losttrinkets:magical_feathers"]
#The trinkets listed in here will also be removed from players that already unlocked them.
blackList = ["losttrinkets:dark_dagger", "losttrinkets:octopus_leg", "losttrinkets:ash_gloves", "losttrinkets:mad_aura", "losttrinkets:blaze_heart", "losttrinkets:tea_leaf", "losttrinkets:coffee_bean", "losttrinkets:oxalis", "losttrinkets:magical_feathers"]
#List of trinkets that can't be unlocked randomly eg: ["losttrinkets:piggy", "losttrinkets:magical_feathers"]
#The trinkets listed in here will not be removed from players that already unlocked them.
nonRandom = []

[Trinket_Slots]
	#Amount of Xp levels added to the next unlocking cost.
	#Range: 0 ~ 1000
	slotUpFactor = 8
	#Maximum number of trinket slots the player can have (does not remove unlocked slots)
	#Range: 1 ~ 40
	maxSlots = 10
	#Numbers of trinket slots the player will start with (Only effect newer players!!).
	#Range: 0 ~ 40
	startSlots = 3
	#Levels of xp needed to unlock a trinket slot.
	#Range: 0 ~ 1000
	slotCost = 18

[Killing_Unlocks]
	#Set to false to disable unlocking trinkets from killing non-Boss entities.
	killingUnlockEnabled = false
	#Rarity of unlocking a trinket from killing non-Boss entities. (Greater number = more rare)
	#Range: 2 ~ 100000
	killing = 100000

[Bosses_Killing_Unlocks]
	#Set to false to disable unlocking trinkets from killing Bosses.
	bossKillingUnlockEnabled = true
	#Rarity of unlocking a trinket from killing Bosses. (Greater number = more rare)
	#Range: 2 ~ 100000
	bossKilling = 2

[Farming_Unlocks]
	#Set to false to disable unlocking trinkets from farming.
	farmingUnlockEnabled = true
	#Rarity of unlocking a trinket from farming. (Greater number = more rare)
	#Range: 2 ~ 100000
	farming = 70

[Ores_Mining_Unlocks]
	#Rarity of unlocking a trinket from mining ores. (Greater number = more rare)
	#Range: 2 ~ 100000
	oresMining = 50
	#Set to false to disable unlocking trinkets from mining ores.
	oresMiningUnlockEnabled = true

[Trading_Unlocks]
	#Rarity of unlocking a trinket from trading. (Greater number = more rare)
	#Range: 2 ~ 100000
	trading = 15
	#Set to false to disable unlocking trinkets from trading.
	tradingUnlockEnabled = true

[Wood_Cutting_Unlocks]
	#Rarity of unlocking a trinket from cutting trees. (Greater number = more rare)
	#Range: 2 ~ 100000
	woodCutting = 85
	#Set to false to disable unlocking trinkets from cutting trees.
	woodCuttingUnlockEnabled = true

