
["Soul Mending"]
	"Soul Mending Spawns Particles" = true
	"Soul Mending Makes a Death Sound When Activating" = true

[Safeguard]
	"Safeguard Spawns Particles" = true
	"Safeguard Makes a Ding When Hit" = true

[Socketed]
	"Colors for Socket Rarities" = ["gray", "dark_green", "blue", "yellow", "light_purple", "gold", "red"]

