
[Effects]
	#Should the Enchanted Book have a different texture when it has any of the Wonderful Enchantments on it? (disabling it may fix some bugs with other mods) (requires game restart)
	enchantment_book_replacement = true

