
#List of ranks
[[ranks]]
	tier = 0
	numAffixes = 0
	defaultColor = 16777215
	chance = 1.0
	growthFactor = 0
	effects = []
	presetAffixes = []

[[ranks]]
	tier = 1
	numAffixes = 1
	defaultColor = 16776960
	chance = 0.3
	growthFactor = 2
	effects = []
	presetAffixes = []

[[ranks]]
	tier = 2
	numAffixes = 2
	defaultColor = 16750848
	chance = 0.1
	growthFactor = 4
	effects = []
	presetAffixes = []

[[ranks]]
	tier = 3
	numAffixes = 2
	defaultColor = 6750207
	chance = 0.1
	growthFactor = 5
	effects = []
	presetAffixes = []

[[ranks]]
	tier = 4
	numAffixes = 3
	defaultColor = 13382655
	chance = 0.1
	growthFactor = 6
	effects = []
	presetAffixes = []

[[ranks]]
	tier = 5
	numAffixes = 3
	defaultColor = 16766515
	chance = 0.0
	growthFactor = 8
	effects = []
	presetAffixes = []

[[ranks]]
	tier = 6
	numAffixes = 4
	defaultColor = 16724787
	chance = 0.0
	growthFactor = 9
	effects = []
	presetAffixes = []

[[ranks]]
	tier = 7
	numAffixes = 4
	defaultColor = 3407359
	chance = 0.0
	growthFactor = 10
	effects = []
	presetAffixes = []

[[ranks]]
	tier = 8
	numAffixes = 4
	defaultColor = 4390656
	chance = 0.0
	growthFactor = 11
	effects = []
	presetAffixes = []

[[ranks]]
	tier = 10
	numAffixes = 5
	defaultColor = 0
	chance = 0.0
	growthFactor = 12
	effects = []
	presetAffixes = []

